# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: MPL-2.0
---
- name: Copy iptables rules file
  copy:
    src: iptables.rules
    dest: "{{ '/etc/systemd/scripts/ip4save' if ansible_os_family == 'VMware Photon OS' else '/etc/iptables/rules.v4' }}"
    mode: 0644

- name: Copy ip6tables rules file
  copy:
    src: ip6tables.rules
    dest: "{{ '/etc/systemd/scripts/ip6save' if ansible_os_family == 'VMware Photon OS' else '/etc/iptables/rules.v6' }}"
    mode: 0644

- name: Save to persist iptables rules
  shell: "iptables-restore < /etc/iptables/rules.v4"
  when: ansible_os_family == "Debian"

- name: Save to persist ip6tables rules
  shell: "ip6tables-restore < /etc/iptables/rules.v6"
  when: ansible_os_family == "Debian"

- name: Save to persist iptables rules
  shell: "iptables-restore < /etc/systemd/scripts/ip4save"
  when: ansible_os_family == "VMware Photon OS"

- name: Save to persist ip6tables rules
  shell: "ip6tables-restore < /etc/systemd/scripts/ip6save"
  when: ansible_os_family == "VMware Photon OS"

- name: Ignore ICMP echo requests (pings) sent to broadcast or multicast addresses
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: "1"
    state: present
    sysctl_set: true

- name: Enable GARP notification on all devices
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_notify
    value: "1"
    state: present
    sysctl_set: true
  when: enable_garp_notify_all | bool
