# © Broadcom. All Rights Reserved.
# The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MPL-2.0
---
- name: Create afterdbus.conf
  copy:
    src: files/etc/systemd/system/vmtoolsd.service.d/afterdbus.conf
    dest: /etc/systemd/system/vmtoolsd.service.d/afterdbus.conf
    mode: 0644

- name: Disable DHCP on the network interface
  file:
    path: "/etc/systemd/network/99-dhcp-en.network"
    state: absent

- name: Enable Apparmor service
  systemd:
    name: apparmor
    daemon_reload: yes
    enabled: true
    state: restarted

- name: Enable Apparmor in kernel
  replace:
    path: /boot/photon.cfg
    regexp: "apparmor=0"
    replace: "apparmor=1"

- name: Enable POS flag in kernel
  lineinfile:
    path: /boot/photon.cfg
    backrefs: yes
    regexp: "^(?!.*pos=1)(photon_cmdline.*)"
    line: '\1 pos=1'

- name: Mask systemd-timesyncd unit
  ansible.builtin.systemd:
    masked: true
    name: systemd-timesyncd.service

- name: Disable OpenSSL FIPS module loading by default
  ansible.builtin.file:
    path: /etc/ssl/provider_fips.cnf
    state: absent

- name: Fix motd permission issue
  ansible.builtin.lineinfile:
    path: /etc/pam.d/motdgen
    line: " session     required      pam_exec.so /usr/bin/chmod a+r /var/run/motdgen/motd"

- name: Remove duplicate artifactory repo
  ansible.builtin.file:
    path: /etc/yum.repos.d/artifactory-photon-5.repo.disabled
    state: absent

- name: add logrotate config for rsyslog
  copy:
    src: files/etc/logrotate.d/rsyslog_no_su
    dest: /etc/logrotate.d/rsyslog
    mode: 0644

- name: Ensure logrotate systemd override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/logrotate.timer.d
    state: directory
    mode: '0755'

- name: update logrotate timer config
  copy:
    src: files/etc/logrotate.d/override.conf
    dest: /etc/systemd/system/logrotate.timer.d/override.conf
    mode: 0644
  register: timer_override_file

- name: Reload systemd daemon to recognize new configuration
  ansible.builtin.systemd:
    daemon_reload: true
  when: timer_override_file.changed

- name: Re-enable and start the logrotate timer
  ansible.builtin.systemd:
    name: logrotate.timer
    enabled: true
    state: restarted
  when: timer_override_file.changed
