# (c) Broadcom. All Rights Reserved.
# The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MPL-2.0
---
- name: Retag Container Images
  script: files/scripts/image_retag.py --k8sSemver {{ kubernetes_semver }} --dockerVersion {{ dockerVersion }} --family "{{ ansible_os_family }}"
  args:
    executable: python3

- name: Start docker registry
  shell: 'ctr -n k8s.io run -d --null-io --net-host --mount type=bind,src=/storage/container-registry,dst=/var/lib/registry,options=rbind:rw docker.io/vmware/docker-registry:{{ dockerVersion }} docker-registry /bin/registry serve /etc/docker/registry/config.yaml'

- name: Copy carvel packages and images to Embedded registry
  script: files/scripts/utkg_download_carvel_packages.py --addonImageList {{ addon_image_list }} --addonLocalImageList {{ localhost_addon_image_list }}
  args:
    executable: python3

- name: Pin container images
  ansible.builtin.script: files/scripts/docker_registry_ops.py --pin
  args:
    executable: python3

- name: Stop docker registry
  shell: 'ctr -n k8s.io task kill docker-registry'

- name: List images
  shell: 'CONTAINERD_NAMESPACE="k8s.io" ctr --address=/var/run/containerd/containerd.sock images ls -q'
  register: container_list

- name: Print containers
  debug:
    var: container_list.stdout_lines